// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 窓口に問い合わせて分かった、アカウントの様子
 */
export type AccountStatus = { email: string, 
/**
 * 残りの割合（切り上げ。使い切ったときだけ 0）
 */
remainingPercent: number, };
