// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 失敗したときに画面へ渡すもの。code は符号（actions.rs の Failure::code）。
 * detail は実行先自身の言葉（actions.rs の ActionError::screen_detail）。
 * 利用者自身の下書きの断片を含みうるのでログには残さず、画面にだけ渡す。exit_code はコマンドの終了コード
 */
export type ActionFailure = { code: string, detail: string | null, exitCode: number | null, };
