// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アクションの結果の出し方。
 * コマンドが下書きを使うか、結果を返すかは Mawok から見分けられないので、アクションごとに持つ
 */
export type ActionOutput = "replace" | "insert" | "none";
