// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * コマンドのアクションとやりとりする文字コード（docs/actions.md「コマンド」）。標準入力へ渡す文と、標準出力を読むときに使う。
 * Windows の `sort` のように、UTF-8 ではなくシステムの文字コード（日本語なら Shift_JIS）で読み書きするコマンドがあるため、アクションごとに持つ
 */
export type ActionEncoding = "utf-8" | "shift_jis" | "euc-jp" | "iso-2022-jp" | "utf-16le";
