// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionEncoding } from "./ActionEncoding";
import type { ActionOutput } from "./ActionOutput";

/**
 * アクションの1件。一覧から選ぶと、コマンドの行を実行して結果を下書きに出す
 */
export type Action = { 
/**
 * 同期でこの1件を見分けるランダムな値
 */
id: string, 
/**
 * 一覧で選ぶときの見出し。空なら、画面側でコマンドの行を代わりに出す
 */
name: string, 
/**
 * 1行のコマンド。行頭が `@ai` なら AI のアクション（actions.rs の ai_instruction）。空なら一覧に出さない
 */
command: string, output: ActionOutput, 
/**
 * コマンドの標準入力と標準出力の文字コード。`@ai` の行では使わない
 */
encoding: ActionEncoding, 
/**
 * 消さずに一覧から外せるようにするため、1件ずつ切れる（置き換え辞書と同じ）
 */
enabled: boolean, 
/**
 * ほかのデバイスと同期するか
 */
sync: boolean, };
