// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AI のアクションに使う AI サービス。足すときは、ここに名前・既定のモデル・資格情報の名前・送る処理を足す
 */
export type AiService = "none" | "mawok" | "gemini" | "anthropic" | "openai";
