// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KatakanaWidth } from "./KatakanaWidth";
import type { WidthStyle } from "./WidthStyle";

/**
 * 文字の種類ごとの、全角と半角の揃え方
 */
export type CharWidths = { alphabet: WidthStyle, digit: WidthStyle, space: WidthStyle, symbol: WidthStyle, katakana: KatakanaWidth, };
