// This file is generated by src-tauri/src/bindings.rs::writes_constants. Do not edit it manually.
export const CONSTANTS = {
	DEFAULT_DRAFT_FONT_SIZE: 16,
	MIN_DRAFT_FONT_SIZE: 10,
	MAX_DRAFT_FONT_SIZE: 32,
	DEFAULT_DRAFT_HISTORY_SIZE: 50,
	MAX_DRAFT_HISTORY_SIZE: 100,
	AI_SERVICES: ["none", "mawok", "gemini", "anthropic", "openai"],
	DRAFT_ACTIONS: ["copy", "send", "settings", "snippets", "actions", "historyOlder", "historyNewer", "sendTargets", "insertReceived", "discardReceived"],
	SUPPORTED_CODES: ["Digit0", "Digit1", "Digit2", "Digit3", "Digit4", "Digit5", "Digit6", "Digit7", "Digit8", "Digit9", "KeyA", "KeyB", "KeyC", "KeyD", "KeyE", "KeyF", "KeyG", "KeyH", "KeyI", "KeyJ", "KeyK", "KeyL", "KeyM", "KeyN", "KeyO", "KeyP", "KeyQ", "KeyR", "KeyS", "KeyT", "KeyU", "KeyV", "KeyW", "KeyX", "KeyY", "KeyZ", "Numpad0", "Numpad1", "Numpad2", "Numpad3", "Numpad4", "Numpad5", "Numpad6", "Numpad7", "Numpad8", "Numpad9", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "F13", "F14", "F15", "F16", "F17", "F18", "F19", "F20", "F21", "F22", "F23", "F24", "Backquote", "Backslash", "BracketLeft", "BracketRight", "Comma", "Equal", "Minus", "Period", "Quote", "Semicolon", "Slash", "Backspace", "CapsLock", "Enter", "Space", "Tab", "Delete", "End", "Home", "Insert", "PageDown", "PageUp", "Pause", "PrintScreen", "ScrollLock", "ArrowDown", "ArrowLeft", "ArrowRight", "ArrowUp", "NumLock", "NumpadAdd", "NumpadDecimal", "NumpadDivide", "NumpadEnter", "NumpadEqual", "NumpadMultiply", "NumpadSubtract", "Escape", "AudioVolumeDown", "AudioVolumeUp", "AudioVolumeMute", "MediaPlay", "MediaPause", "MediaPlayPause", "MediaStop", "MediaTrackNext", "MediaTrackPrevious"],
	AI_PREFIX: "@ai",
	TEXT_MARK: "{{t}}",
	NEW_ACTION: {"name":"","command":"","output":"replace","encoding":"utf-8","enabled":true}
} as const;

export const EVENTS = {
	SETTINGS_CHANGED: "settings-changed",
	DRAFT_HISTORY_CLEARED: "draft-history-cleared",
	SNIPPET_ADDED: "snippet-added",
	PAIRING_CODE_ENDED: "pairing-code-ended",
	DRAFT_RECEIVED: "draft-received",
	SHOWN: "shown",
	HIDE_REQUESTED: "hide-requested",
	DRAFT_HIDDEN: "draft-hidden",
	MAWOK_SIGN_IN_ENDED: "mawok-sign-in-ended",
	UPDATE_CHANGED: "update-changed"
} as const;
