// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 同じアカウントで見つけた自分のデバイス（docs/lan.md「同じ LAN の自分のデバイスへ送る」）
 */
export type Device = { 
/**
 * ペアリングか生存確認で相手が名乗った名前
 */
name: string, 
/**
 * 相手の公開鍵（小文字の16進）。この鍵を持つ相手とだけ送り合う
 */
publicKey: string, 
/**
 * 最後に相手へ送れた、または生存確認したときのアドレス。起動した直後で、相手の名乗りがまだ届いていないときに使う
 */
address: string, 
/**
 * 送信先にチェックを入れているか。送るキーとボタンは、チェックしたデバイスへ送る
 */
sendTo: boolean, };
