// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 操作ごとのキー。ホットキーと同じ書き方（`CommandOrControl+Shift+Enter`）で、空文字は割り当てなし
 */
export type DraftKeys = { copy: string, send: string, settings: string, snippets: string, actions: string, historyOlder: string, historyNewer: string, sendTargets: string, insertReceived: string, discardReceived: string, };
