// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 欄で Tab を押したときに補った結果
 */
export type FolderCompletion = { 
/**
 * 補った後の欄の中身
 */
input: string, 
/**
 * 当てはまるフォルダーが2つ以上のときの名前（並べ替えて、上限まで）
 */
candidates: Array<string>, 
/**
 * 当てはまるフォルダーの数
 */
total: number, };
