// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderItem = { 
/**
 * フォルダーの名前（パスの最後）
 */
name: string, 
/**
 * タイトルバーと同じ形のパス（display）
 */
display: string, 
/**
 * 移るときに change_folder に渡すパス
 */
path: string, };
