// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderItem } from "./FolderItem";

/**
 * テキストウィンドウの下のフォルダーのボタンとメニューに出すもの
 */
export type FolderMenu = { current: FolderItem, 
/**
 * 今のフォルダーがホームか。ボタンには名前でなく「ホーム」と出す
 */
atHome: boolean, 
/**
 * 最近移ったフォルダー（新しい順。今のフォルダーも含み、ホームは含まない。まだあるかは確かめていない）
 */
recent: Array<FolderItem>, };
