// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * カタカナは全角に揃えるだけにする。半角カナは文字化けしやすく、揃えたい場面が考えにくいため
 */
export type KatakanaWidth = "keep" | "full";
