// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mawok のアカウントと結ぶ申し込みが終わった（MAWOK_SIGN_IN_ENDED の中身）。結べたら true、期限が切れたか失敗したら false。
 * 画面は、出している申し込みと同じ番号の知らせだけを受ける（やり直す前の申し込みの終わりで、表示を戻さないため）
 */
export type MawokSignInEnded = { id: number, signedIn: boolean, };
