// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mawok のアカウントと結ぶ申し込み。終わりの知らせと組にする番号
 */
export type MawokSignIn = { 
/**
 * 申し込みの番号。終わりの知らせ（MawokSignInEnded）に同じ番号が付く
 */
id: number, };
