// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 組み合わせた自分の機器（docs/lan.md「同じ LAN の自分の機器へ送る」）
 */
export type PairedDevice = { 
/**
 * 組み合わせたときに相手が名乗った名前
 */
name: string, 
/**
 * 相手の公開鍵（小文字の16進）。この鍵を持つ相手とだけ送り合う
 */
publicKey: string, 
/**
 * 最後に相手へ送れた、または組み合わせたときのアドレス。起動した直後で、相手の名乗りがまだ届いていないときに使う
 */
address: string, 
/**
 * 送信先にチェックを入れているか。送るキーとボタンは、チェックした機器へ送る
 */
sendTo: boolean, };
