// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画面が OS ごとにキーの表記や閉じるキーを変えるときも、この名前（`macos`・`windows`）で渡す
 */
export type Platform = "macos" | "windows";
