// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 窓口が答えた Pro の状態。試用中も active になる。
 */
export type ProStatus = { active: boolean, until: number | null, plan: string | null, trial: boolean, };
