// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 句読点をどちらに揃えるか。
 * 半角の `,` `.` は数や小数点、コードに出るので対象にしない。全角どうしの行き来だけを扱う
 */
export type PunctuationStyle = "keep" | "kutouten" | "comma";
