// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 同じアカウントのデバイスから届いた下書き（画面側の draft-received）
 */
export type ReceivedDraft = { 
/**
 * 送ってきたデバイスの名前
 */
from: string, text: string, };
