// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 置き換え辞書の1件。音声入力のよくある誤変換を直す（例: 「濃度」→「Node.js」）
 */
export type Replacement = { 
/**
 * 同期でこの1件を見分けるランダムな値
 */
id: string, 
/**
 * 置き換える前の文字列
 */
from: string, 
/**
 * 置き換えた後の文字列
 */
to: string, 
/**
 * 誤って巻き込む語を辞書から消さずに止められるようにするため、1件ずつ切れる
 */
enabled: boolean, 
/**
 * ほかのデバイスと同期するか
 */
sync: boolean, };
