// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `apply_replacements` が置き換える範囲。`start`・`len` は文字数（コードポイント単位。UTF-16 コード単位ではない）で、
 * JS 側で `String.prototype.at` 相当の文字単位インデックスとして使う想定（サロゲートペアが絡む文字は対象外）。
 * `to` は置き換えた後の文字列（ホバーでの案内表示用）
 */
export type ReplacementMatch = { start: number, len: number, to: string, };
