// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 送れなかったときに画面へ渡すもの。一部の機器にだけ届かなかったら、符号は `lan.partial` で、届かなかった機器の公開鍵を添える
 */
export type SendFailure = { code: string, devices: Array<string>, };
