// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { AiService } from "./AiService";
import type { CharWidths } from "./CharWidths";
import type { Device } from "./Device";
import type { DraftKeys } from "./DraftKeys";
import type { Language } from "./Language";
import type { Platform } from "./Platform";
import type { PunctuationStyle } from "./PunctuationStyle";
import type { Replacement } from "./Replacement";
import type { Snippet } from "./Snippet";
import type { Status } from "./Status";
import type { Theme } from "./Theme";

/**
 * `get_settings` と `settings-changed` で画面側に渡す設定。
 */
export type SettingsView = { 
/**
 * 何回目に渡した設定か。画面は、コマンドの返事より前の設定か後の設定かを、これで見分ける
 */
revision: number, 
/**
 * 下書きウィンドウを出すグローバルホットキー
 */
hotkey: string, textWindowKeys: DraftKeys, 
/**
 * 「既定に戻す」を押せるかを見るための既定のキー。既定は Rust 側だけで決める
 */
defaultDraftKeys: DraftKeys, 
/**
 * ホットキーの「既定に戻す」で戻すキー
 */
defaultHotkey: string, 
/**
 * ログイン時に起動するか
 */
autostart: boolean, language: Language, theme: Theme, 
/**
 * 下書きウィンドウを常に最前面に表示するか
 */
textWindowAlwaysOnTop: boolean, 
/**
 * 下書きウィンドウからフォーカスが外れたら、コピーせずに隠すか
 */
hideTextWindowOnBlur: boolean, 
/**
 * 下書きの入力欄の上下に、操作のボタンを出すか
 */
showTextWindowButtons: boolean, 
/**
 * 下書きの履歴の件数。0 なら覚えない
 */
textHistorySize: number, trimTrailingWhitespace: boolean, replacements: Array<Replacement>, 
/**
 * 定型文。登録した順
 */
snippets: Array<Snippet>, 
/**
 * 同じアカウントで見つけた自分の機器。見つけた順
 */
devices: Array<Device>, 
/**
 * ペアリングと生存確認で相手へ名乗る、この機器の名前
 */
deviceName: string, 
/**
 * 機器の間の送受信を使える Pro か
 */
proAvailable: boolean, accountKeyStatus: Status, 
/**
 * Mawok のアカウントトークンを資格情報管理から読めたか
 */
mawokAccountSignedIn: boolean, punctuationStyle: PunctuationStyle, charWidths: CharWidths, 
/**
 * コピーするときに、クリップボードの履歴・同期・管理アプリに残さないよう印を付けるか
 */
excludeFromClipboardHistory: boolean, 
/**
 * 下書きの入力欄のフォント。CSS の font-family の並び。空なら OS 標準
 */
textFontFamily: string, 
/**
 * 下書きの入力欄の文字の大きさ（px）
 */
textFontSize: number, 
/**
 * 下書きの入力欄の案内。None なら既定の案内（文言は画面側で今の言語とホットキーから作る）
 */
inputGuidance: string | null, 
/**
 * 下書きの入力欄の文字色（ライト）。小文字の #rrggbb。空なら標準の色
 */
textColorLight: string, 
/**
 * 下書きの入力欄の文字色（ダーク）。小文字の #rrggbb。空なら標準の色
 */
textColorDark: string, aiService: AiService, 
/**
 * 送る内容と扱いを了解した AI サービス
 */
aiConsent: AiService | null, 
/**
 * AI サービスごとに設定したモデル。書いていないサービスは既定のモデル
 */
aiModels: { [key in AiService]?: string }, 
/**
 * AI サービスごとの既定のモデル。既定は Rust 側だけで決める
 */
defaultAiModels: { [key in AiService]?: string }, 
/**
 * アクションの並び。設定ファイルに書いていなければ、今の表示言語の既定のアクション
 */
actions: Array<Action>, 
/**
 * アプリのバージョン。ログの先頭に出しているものと同じ
 */
version: string, 
/**
 * 表示言語の設定と OS の言語から決めた Paraglide のロケール
 */
locale: string, 
/**
 * 画面は OS ごとにキーの表記や閉じるキーを変える
 */
platform: Platform, };
