// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 定型文の1件。下書きで定型文のキー（既定は Cmd+J、Windows は Ctrl+J）で出す一覧から選び、カーソルの位置に差し込む
 */
export type Snippet = { 
/**
 * 同期でこの1件を見分けるランダムな値
 */
id: string, 
/**
 * 一覧で選ぶときの見出し。空なら、画面側で本文の最初の空でない行を代わりに出す
 */
name: string, 
/**
 * 差し込む文。複数行にできる
 */
body: string, 
/**
 * ほかのデバイスと同期するか
 */
sync: boolean, };
