// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateStatus } from "./UpdateStatus";

/**
 * `update_status` と `update-changed` で設定の画面へ渡すもの
 */
export type UpdateView = { status: UpdateStatus, 
/**
 * 下書きウィンドウに書きかけの文があるか。あれば、再起動で消えることを更新のボタンの近くに出す
 */
draftHasText: boolean, };
