// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 新しい版を確かめ、入れる様子
 */
export type UpdateStatus = { "state": "unchecked" } | { "state": "checking" } | { "state": "upToDate" } | { "state": "available", version: string, } | { "state": "installing", version: string, } | { "state": "checkFailed" } | { "state": "installFailed", version: string, };
