// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 英字・数字・空白・記号を、全角と半角のどちらに揃えるか
 */
export type WidthStyle = "keep" | "full" | "half";
