//! `cargo test` で画面向けの定数を書き出す。

use std::{env, fs, path::PathBuf};

use crate::{actions, ai, config, draft_keys, events};

#[test]
fn writes_constants() {
    let export_dir = PathBuf::from(env::var("TS_RS_EXPORT_DIR").expect("TS_RS_EXPORT_DIR is set"));
    fs::create_dir_all(&export_dir).expect("could not create bindings directory");
    let action_names: Vec<String> = draft_keys::DraftAction::ALL
        .into_iter()
        .map(|action| config::choice_name(&action))
        .collect();
    let ai_services: Vec<String> = ai::AiService::ALL
        .into_iter()
        .map(|service| service.name().to_string())
        .collect();
    let new_action =
        serde_json::to_string(&config::Action::default()).expect("could not serialize Action");
    let contents = format!(
        "// This file is generated by src-tauri/src/bindings.rs::writes_constants. Do not edit it manually.\n\
export const CONSTANTS = {{\n\
\tDEFAULT_DRAFT_FONT_SIZE: {},\n\
\tMIN_DRAFT_FONT_SIZE: {},\n\
\tMAX_DRAFT_FONT_SIZE: {},\n\
\tDEFAULT_DRAFT_HISTORY_SIZE: {},\n\
\tMAX_DRAFT_HISTORY_SIZE: {},\n\
\tAI_SERVICES: {:?},\n\
\tDRAFT_ACTIONS: {:?},\n\
\tSUPPORTED_CODES: {:?},\n\
\tAI_PREFIX: {:?},\n\
\tTEXT_MARK: {:?},\n\
\tNEW_ACTION: {}\n\
}} as const;\n\n\
export const EVENTS = {{\n\
\tSETTINGS_CHANGED: {:?},\n\
\tDRAFT_HISTORY_CLEARED: {:?},\n\
\tSNIPPET_ADDED: {:?},\n\
\tPAIRING_CODE_ENDED: {:?},\n\
\tDRAFT_RECEIVED: {:?},\n\
\tSHOWN: {:?},\n\
\tHIDE_REQUESTED: {:?},\n\
\tDRAFT_HIDDEN: {:?},\n\
\tMAWOK_SIGN_IN_ENDED: {:?},\n\
\tUPDATE_CHANGED: {:?}\n\
}} as const;\n",
        config::DEFAULT_DRAFT_FONT_SIZE,
        config::MIN_DRAFT_FONT_SIZE,
        config::MAX_DRAFT_FONT_SIZE,
        config::DEFAULT_DRAFT_HISTORY_SIZE,
        config::MAX_DRAFT_HISTORY_SIZE,
        ai_services,
        action_names,
        draft_keys::SUPPORTED_CODES,
        actions::AI_PREFIX,
        actions::TEXT_MARK,
        new_action,
        events::SETTINGS_CHANGED,
        events::DRAFT_HISTORY_CLEARED,
        events::SNIPPET_ADDED,
        events::PAIRING_CODE_ENDED,
        events::DRAFT_RECEIVED,
        events::SHOWN,
        events::HIDE_REQUESTED,
        events::DRAFT_HIDDEN,
        events::MAWOK_SIGN_IN_ENDED,
        events::UPDATE_CHANGED,
    );
    fs::write(export_dir.join("constants.ts"), contents).expect("could not write constants.ts");
}
